import images from "~/assets/images";

export const courseData = [
    {
        id: "t1",
        ttl: "Getting Started",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t11",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
                resources: [
                    {
                        id: "t111",
                        text: "CSS file",
                        link: "https://github.com/",
                        icon: images.teachIcon,
                        downloadable: false,
                    },
                ],
            },
            {
                id: "t12",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
                resources: [
                    {
                        id: "t112",
                        text: "css file",
                        link: "https://github.com/",
                        icon: images.teachIcon,
                        downloadable: true,
                    },
                ],
            },
            {
                id: "t13",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
                resources: [
                    {
                        id: "t113",
                        text: "css file",
                        link: "https://github.com/",
                        icon: images.teachIcon,
                        downloadable: false,
                    },
                    {
                        id: "t114",
                        text: "html file",
                        link: "https://github.com/",
                        icon: images.teachIcon,
                        downloadable: false,
                    },
                ],
            },
            {
                id: "t14",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t15",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t16",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t17",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t18",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t2",
        ttl: "Javascript Refresherrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t21",
                ttl: "Welcome to the Course!",
                dur: "34:56",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t22",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t23",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t24",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t25",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t26",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t27",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t28",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t3",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t31",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t32",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t33",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t34",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t35",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t36",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t37",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t38",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t4",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t41",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t42",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t43",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t44",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t45",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t46",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t47",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t48",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t5",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t51",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t52",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t53",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t54",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t55",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t56",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t57",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t58",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t6",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t61",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t62",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t63",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t64",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t65",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t66",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t67",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t68",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t7",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t71",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t72",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t73",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t74",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t75",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t76",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t77",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t78",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
    {
        id: "t8",
        ttl: "Javascript Refresher",
        lects: "10",
        dur: "41min",
        list: [
            {
                id: "t81",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t82",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t83",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t84",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t85",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "doc",
                desc: "This is a sample document description.",
            },
            {
                id: "t86",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: true,
                type: "video",
                desc: "",
            },
            {
                id: "t87",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "video",
                desc: "",
            },
            {
                id: "t88",
                ttl: "Welcome to the Course!",
                dur: "01:04",
                preview: false,
                type: "query",
                desc: "This is a sample document description.",
            },
        ],
    },
];
